### PR TITLE
Range route

### PR DESCRIPTION
**Pull request by mrhut10**
really happy with this, which addresses #45 

* \collections route will show all ranges (3 shown per range)
* `\collections\?range=${rangeName}` will filter to show all products within a particular range
* bottom of each product page shows three other products within the range, and clicking on the range title will take you too the \collections\?range=${rangeName} so you can see all products within this range.

if you've time @lukebennett88 would love you to test the UI for it. but fairly happy that i finally got working :)

### CODE REVIEW

**Comment by lukebennett88** [comment]
Looks good @mrhut10, I made a few minor changes which I'm just about to make a PR to include.
Was also thinking rather than have 'Explore Our Collections', and then an `<hr>` and then the Range name under that — we could change it to `Explore Our ${range} Collection`, but I couldn't work out your ramda stuff to do that 🙃

**Comment by mrhut10** [comment]
mmmm, I tried to impliment "Explore Our ${range} Collection"
however i've seem to broken the dev server just tries to refresh page constantly, but the site works when building and serving.

time to gatsby clean and npm install

**Comment by lukebennett88** [comment]
Hahah, super useful command that one. Fingers crossed that fixes it.

**Comment by mrhut10** [comment]
it didn't i now believe is a browswer cache issue, and haven't multiple conflicting service workers.

shortly i'll clear browser cache and see if that fixes, certainly been a little unuseral problem.

**Comment by lukebennett88** [comment]
I’ve given up on using the Gatsby offline service worker. Too many weird edge cases.
I’ve even had issues with https://www.gatsbyjs.org occasionally not working for me.
Might want to consider adding this plugin: https://www.npmjs.com/package/gatsby-plugin-remove-serviceworker if you’re still having issues.

**Pull request merged**
