### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by lukebennett88**
This is a fairly significant redesign.

I updated the version of Tailwind that was being used, which involved changing a lot of things, so used that as an excuse to give the rest of the site a fresh coat of paint.

I created a new colour palette which was 9 different shades of warm grey, maroon and cream and tried not to use anything else.

I also pulled the cart icon out of the navigation and it now floats to the bottom right of the screen, hopefully it's a little more prominent now, and it's also easier to reach on mobile devices. I was thinking we could probably add a badge to it to indicate if there is anything in the cart or not as well.

I also renamed a lot of things to keep things consistent (hope you don't mind):
- All components are in PascalCase, pages and templates are in snake-case and regular JavaScript files are in camelCase

I broke the React Helmet stuff out of the Layout into it's own component, I was thinking we can probably self host some of this as there is no reason to pull down jQuery from a CDN etc, we can pull it down from npm or from the `/static` folder but didn't get around to it, figured you'd be better able to test it if I messed something up here. I wouldn't mind reskinning Snipcart, but I couldn't get the npm packages for this to work <http://github.com/snipcart/snipcart-theme>.

There are lots of minor changes to the markdown files, mostly just spelling, formatting and making thing consistent between different products, still heaps to do, but very time consuming so only did a bit.

That should cover most of it, sorry for the massive PR, hopefully I didn't break anything 😬

### CODE REVIEW

**Comment by lukebennett88** [comment]
I just realised that the MailChimp popup (which doesn't show up on dev) completely obscures the new cart button. Will have to come up with a different place to put it, or give it a higher z-index.

**Comment by mrhut10** [comment]
man i missed your PR looks massive, thank you.

I'll jump in now. looks like one file in conflict, but i'll play with and see how i go :)

**Comment by mrhut10** [comment]
I figured might be easier plus good git practice, i'm currently merging in commit by commit. so far man you've done a lot even in the first commit. did you write a script to find all my terrible inconsistencies?

**Comment by mrhut10** [comment]
nice use of react icons and getting rid of the blueprint ones :) !!!

**Comment by lukebennett88** [comment]
> man i missed your PR looks massive, thank you.
Whoops, forgot to tag you 😬

> I'll jump in now. looks like one file in conflict, but i'll play with and see how i go :)
Glad there is only 1 conflict — I had a bunch of case sensitivity issues when I was renaming some of the components. Hopefully that’s fixed.

> I figured might be easier plus good git practice, i'm currently merging in commit by commit. so far man you've done a lot even in the first commit. did you write a script to find all my terrible inconsistencies?
Nah, just fixing things on the fly and a bit of find and replace.
That’s why there was a giant ‘init’ commit. Too much To go through 1 by 1 😬

**Comment by mrhut10** [comment]
Ok i've got it all merged into github branch called redesign

I believe the owner is back on Wednesday, but I wont see him till Friday. I'll walk him though it.

I love the shopping cart bubble BTW, on firefox PC doesn't seem to center icon however.

and there was one thing you did with the SEO component i want to go back and look at so i'm on the same page.

and thank you so much you've done a lot of work here, looks really awesome.
can't wait to be able to help you on a project your doing!! @lukebennett88

**Comment by mrhut10** [comment]
the redesign branch is set to build so that we can preview it.

i wasn't able to set the sub-domain yet (don't think netlify has detected the branch yet)

but later today i'll have it set up so that we can see builds on
redesign.futuresfinefurnitureandbedding.com

@lukebennett88

**Comment by mrhut10** [comment]
have a build error, but its my new file under pages
the route
/collections.

i'll fix it tonight :)

**Comment by lukebennett88** [comment]
> I love the shopping cart bubble BTW, on firefox PC doesn't seem to center icon however.

I'll take a look at this when I get a chance, hopefully tonight. I've noticed that SVGs can behave very different between browsers. I also need to bring it in front of the MailChimp banner.

**Comment by mrhut10** [comment]
if get a ok from owner (which i think will be fine) I'll have a go at either of

a) shoping cart count of items number on icon
b) shoping cart hiden on empty
c) empty shopping cart click takes user to a quick add too shopping cart page like maybe most popular items and/or specials.

**Comment by lukebennett88** [comment]
Sounds like a good idea. 

For the MailChimp popup, do you have any controls over the styling of that in the MailChimp backend?
It's pretty close, but there are a few inconsistencies I wouldn't mind fixing if possible (font-stack and size, padding, colours are all just a little off), but since they're in an `<iframe>` I can't get to them to style myself.

**Comment by mrhut10** [comment]
mmm, i'll have a look at the mailchimp side shortly i believe there is styling we can do.
let me know when you've free time, maybe i can get you a mailchimp login thats tied to the account.

**Comment by mrhut10** [comment]
can't for the life of me get netlify to have a redesign subdomain, very odd. I'll raise a support ticket with them.  i have selected build from all branches pushed to repo also :| @lukebennett88 very odd

**Comment by mrhut10** [comment]
got the go ahead @lukebennett88 :) he basically said if we aren't making the site more complicated its fine with me. Think he's happy that someone cares about it like you and I.

we also had our first significant sale on Wednesday, someone brought a $600 mattress and paid for local delivery. I'm yet to fine out if a regular customer or new business.

**Comment by lukebennett88** [comment]
> let me know when you've free time, maybe i can get you a mailchimp login thats tied to the account.

That would be cool if you can, but no rush. Moving house next week and I've got a ton of projects on the go at work now, so don't have a lot of free time at the moment.


> got the go ahead @lukebennett88 :) he basically said if we aren't making the site more complicated its fine with me. Think he's happy that someone cares about it like you and I.

That's great news, would have sucked to sink all that time into it and have him not happy with the design 😜
I still wouldn't mind doing a bit more design work: tidy up the logo, style Snipcart and the Mailchimp and I'm sure there are a few more minor things I'm not thinking of right now, so good to know that's he's basically happy for us to do whatever to the site as long as it's an improvement. Probably won't be able to dedicate any time to it for a while though.

> we also had our first significant sale on Wednesday, someone brought a $600 mattress and paid for local delivery. I'm yet to fine out if a regular customer or new business.

Also great news, hopefully the sales keep coming 😊

**Pull request merged**
