### PR TITLE
Fix button being full width, plus some minor typography tweaks

### PR DESCRIPTION
**Pull request by lukebennett88**
Hopefully this does what you need it to do 🙂
CleanShot 2019-05-31 at 14 08 31@2x

### CODE REVIEW

**Comment by mrhut10** [comment]
man your doing some funky stuff here,
the @ applying a list style, i'll have to get an explanation of that another day.

and thank you so much your a wizard!!! @lukebennett88

**Comment by mrhut10** [comment]
whats the best way with tailwind on those product images to increase the bottom margin slightly??

**Comment by lukebennett88** [comment]
Haha, the @apply is a PostCSS directive — let’s me use a Tailwind classname right in the CSS file. I didn’t actually use they for the list, it was left over from some base typography styles, I just added the `list-style-position: inside;` which stopped the bullets in the list from pushing up against the image.

**Comment by lukebennett88** [comment]
To increase the margin, just find the image and add a class of `mb-4` which is 1 rem (each spacing unit in Tailwind is 1/4 of a rem.)

I can send you a PR when I have time though 😊

**Pull request merged**
