### PR TITLE
Fix hero image and other styling fixes

### PR DESCRIPTION
**Pull request by lukebennett88**
Hey mate, I think I've fixed the hero image not filling the container.
While I was at it, I made a few more style changes. Here are some of the main ones;
- topmenu is now a hamburger menu that will stick to the top of the viewport — better for smaller screens
- Cards now have a coloured header that matches the topmenu and buy now buttons that matches the header
- The item page has been considerably redesigned, including a customised <select> menu
- All images are now `fluid` instead of `fixed`. This prevents the warnings you were getting during build when an image was smaller than the specified width
Hope this is useful to you.

### CODE REVIEW

**Comment by mrhut10** [comment]
@lukebennett88 just looking at the build preview. It looks really amazing and like you've done a lot of work here. Dam. Thankyou.

 feel free to pr straight to master in the future.but when i look though it (likely the middle of tonight) I'll merge it across to master.

**Comment by lukebennett88** [comment]
Awesome, glad you like it.
Just picked up **4 more websites** today. Client wants them done in a month, plus 1 have 2 more that are due start of next month, so might not be able to help out more for a while 😬

**Comment by mrhut10** [comment]
@lukebennett88 that's really great that you've got heaps of work.
Yay!!!

I wish i had more time that is could help more your way. I've got exams first week of June . Then i should have more time. Maybe we can organise a catch up mid June and talk about that auction stuff potential if you wanted too as well.


I'm on roofs all this week, just about to climb one

**Comment by lukebennett88** [comment]
Yeah a meetup in June would be great. Hopefully my workload drops around then as well.

**Comment by mrhut10** [comment]
I'm a bit lost how there is so many commits i've done that appear to not be merged in, i'm just walking though them all now to see if any are redundent.

**Comment by mrhut10** [comment]
merging this one from commandline was really odd. No Idea what i was missing..

* firstly checkout the remote branch
'''git checkout lukebennett88_master'''
* secondly i merged master into it to remote redundant commits
'''git merge master'''
* thirdly i pushed back to the branch
'''git push'''

I expected this to remote all the redundant commits from me, however it did not.


but then after i made a PR #34 to merge this into master it only showed your commits as i was trying to do here.

after merging your lukebennett88:master into my master, then merging my master back into mrhut10:lukebennett88_master it correctly merged.

anyway i'm not sure if i'm describing what happened here very well. might just quite explaining here.


:)

**Pull request merged**
