### PR TITLE
Lukebennett88 master

### PR DESCRIPTION
**Pull request by lukebennett88**
Huge PR.
- Every file has been run through Prettier/ESLint or Markdownlint
- Every image has been losslessly compressed using SVGOMG and ImageOptim
- Added Tailwind CSS framework for lightweight styling
- Made style changed to entire site, consistent colours, typography
- Lazy loaded map on contact page using react-lazyload npm package
- Style cards for and images

Probably a bunch of other things too.

The one problem I am still having is with the hero image on the home page, there is some whitespace visible at some breakpoints. I think this is because the image is too small, are we able to get a higher res image? gatsby-image will serve an optimised version so size shouldn't be an issue.

### CODE REVIEW

**Comment by mrhut10** [comment]
how did i completely miss that you'd already submitted a PR.

my hugest appologies for my comment 10 mins ago. I'll try merge this in. :)

thank you so much.

**Comment by lukebennett88** [comment]
No dramas. Good luck merging it in 😝 
[Website is starting to look really good now](https://futures-fine-furniture.netlify.com)

**Comment by mrhut10** [comment]
man so far the half of it i've look at looks really good.

really interested in learning the tailwind css stuff now. like that you've negated my use of <Card/> from blueprintJs.

and better image, we could replace the Hero image when any nice picture of future as long as the owner doesn't dislike it. What size / aspec ratio do you think will fix the issue your seeing?

**Comment by lukebennett88** [comment]
Not too sure, I’ll have a play around when I’m not at work.
I’ve built similar looking headers before and never had as much trouble as I’ve had with this one.
Worst part is it only shows up on the built site, not on the Gatsby dev server which makes debugging it pretty tedious.
The hero image that is being used is only 944 × 519 and the hero component is 60rem (960px) so it needs to be at least that big, probably a fair bit bigger to give it room to breathe.
I noticed almost all of the other images are extremely small too, if we can get higher res photos that would be ideal, let gatsby-image do the heavy lifting of serving the right size.
If you’re worried about having too many images in your repo, this might be worth looking into: https://www.netlify.com/blog/2019/02/26/manage-your-code-and-assets-together-with-netlify-large-media/
Happy to show you the ropes with Tailwind, it’s pretty much my favourite thing, thats why I gave a talk on it at the WordPress meetup 😜

**Comment by mrhut10** [comment]
Hell yes would i like a bring up to speed on tailwind,

**Comment by mrhut10** [comment]
thought i'd quickly ask, @lukebennett88 

the linking and checking you did with some markdown, eslint or/and prettier. what do i need to install to get that running locally on my end?

as i'm sure my commits I've made sense this merge haven't followed the linting standards you implemented. :(

**Comment by lukebennett88** [comment]
I've been using @wesbos ESLint settings for my JavaScript: https://github.com/wesbos/eslint-config-wesbos

For Markdown I use: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

For my exact setup I have a dotfiles repo set up here: https://github.com/lukebennett88/dotfiles

**Pull request merged**
